<?php

return array(
    'multimedia' => array(),
    'directory' => array(),
    'documents' => array(),
    'glossary' => array(),
    'menus' => array(),
    'sections' => array(),
    'maillist' => array(),
    'articles' => array(),
    'votes' => array(),
    'persons' => array(),
    'writers' => array(),
    'users' => array(),
    'sms' => array(),
    'infocus' => array(),
    'issues' => array(),
    'events' => array(),
    'uploads' => array('inCore'=>true),
    'install' => array('inCore'=>true, 'moduleManageTarget'=>2),
    'workflow' => array('inCore'=>true),
    'settings' => array('inCore'=>true),
    'rss' => array(),
    'jobs' => array(),
    'tenders' => array(),
    'logger' => array('inCore'=>true),
    'issues' => array('inCore'=>true),
);
